# Generated by Django 3.0.3 on 2020-09-03 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
